services:
  app:
    image: ghcr.io/${REPO_OWNER}/megacampaignservice:latest
    container_name: megacampaign-app
    ports:
      - "${API_PORT}:8080"
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      AUTH_SERVICE_URL: ${AUTH_SERVICE_URL}
      ADMIN_DISCORD_ID: ${ADMIN_DISCORD_ID}
    restart: unless-stopped

  postgres:
    image: postgres:18.1
    container_name: megacampaign-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    restart: unless-stopped

volumes:
  pgdata:
